language: go
go: 
  - "1.15.x"

env:
  - GO111MODULE=on

matrix:
  include:
    - os: windows
      script:
        - cd bin/stitch
        - go test
        - go build
        - cd ../..
      before_deploy: ./scripts/pack_windows.x86.bat
      cache:
        directories:
          - $HOME/AppData/Local/go-build
          - $HOME/gopath/pkg/mod

install: true

deploy:
  provider: releases
  api_key:
    secure: WgV4aKAP1PnvUSY/2OKAILC53Fft4EVxJvxOqxkPIEV/BzcukRSD/piDEEkrUuQ0y4t1UakA5I1+zxmthv7IRXyA1QRcvXQyox0+p+EmxM+EZObiTZHqPna4dwvZOEoiMRZ2dKsztMTrKyHGJS5eREeqlmyQaa95MFT2mCaPj6i6MXjO2khipg/RFNY+dCWDflvDCtti1ssAfgd19GmMd+89jpS5eg7UoZjISdRtKott7CVdNk3sPHVyg+Gnm8Qog5dXkRxhiFWXrKJOeNfBbVUz6GbDYtKTp8kibec2pzYttkyhqrdLChj/FOZxfRe6pwOJ187HMYFFQck0tQWG4wll0q0QtJ+tOilnk4FlGgLWJQA8sBCvmihHxTHhVRa7e/JkMWLtsA1lkHdrXNLK+av7Fv1JZea6XOq4JuXIkqnIvIEehibBJBepTMXI44zxkpELcQ8sZZTuyizxRxZaqgHCRebfhIC/+UhZeoztvntQdFHuDg/1Cnq/H0sMZhSsAUkM9Rbe2+bSXCXAy2pmDutJxYlP3lIX65pB8VU8CbXAMxegcjOMdIay4bZ3hC/ObLLvdHtA9pXVbg/PGWAaSzWXZCEk9fX83sWz7rcr0lEQPYdGEAxLUVUhxY7fgWzUU3BWNtgdsad7UlIrBkze9VjGYocE+g5I5AIBshB4qrY=
  file:
    - "./distribution/Windows.x86.7z"
  skip_cleanup: true
  draft: true
  on:
    tags: true