name: Build and test

on: [push, pull_request]

jobs:

  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.21

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
          submodules: recursive

    - name: Build stitch tool
      run: go build -v .
      working-directory: ./bin/stitch

    - name: Test stitch tool
      run: go test -v .
      working-directory: ./bin/stitch
